pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven("https://jitpack.io")
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven("https://jitpack.io")
    }
}
rootProject.name = "YACSA"

include(":app")
include(":feature:books")
include(":feature:format")
include(":feature:person")
include(":feature:main")
include(":feature:navigation")
include(":feature:onboarding")
include(":feature:featureflagmanager")
include(":feature:notfound")
include(":feature:search")
include(":feature:settings")
include(":feature:analytics")
include(":core:common")
include(":core:platform")
include(":core:ui")
include(":core:model")
include(":core:localization")
include(":domain")
include(":domain:impl")
include(":data")
include(":data:network")
include(":data:network:impl")
include(":data:datastore")
include(":data:datastore:impl")
include(":data:database")
include(":data:database:impl")
include(":data:cryptodatastore")
include(":data:cryptodatastore:impl")
include(":data:remoteconfig")
include(":data:remoteconfig:impl")
include(":data:repository")
include(":data:repository:impl")
include(":service")
include(":service:analytics")
include(":service:featureflag")
include(":service:featureflag:impl")
include(":service:analytics")
include(":service:analytics:dispatcher")
include(":service:analytics:dispatcher:impl")
include(":service:analytics:provider")
include(":service:analytics:provider:impl")
include(":service:analytics:provider:impl:local")
include(":service:analytics:provider:impl:notification")
include(":service:analytics:provider:impl:firebase")
include(":service:flipper")
